logging:
  level:
    lu:
      atoz:
        main: debug
server:
  port: 8080
security:
  keytab:
    file: C:/tomcat.keytab
  service:
    principal: HTTP/applicationhost.TESTDOMAIN.INTERNAL@TESTDOMAIN.INTERNAL