spring:
  datasource:
    url: jdbc:sqlserver://192.168.100.32;databaseName=intranet_main
    username: sa
    password: Findl123++
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true